---
title: "Homework5"
author: "Khalid Al-Lakhen"
date: "2023-11-29"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(stringr)
library(forcats)
library(broom)
library(purrr)
library(maps)
```

```{r}
install.packages("sf")
install.packages("tigris")
library(sf)
library(tigris)
```

# getting maps 

```{r}
nm_counties <- counties(state = "NM", cb = TRUE, class = "sf")
class(nm_counties)
nm_counties %>% 
  slice(1:3)
```

```{r}
bernalillo_county <- nm_counties %>%      #Let's filter to only bernalillo county
  filter(NAME %in% c("Bernalillo"))
bernalillo_county


```


```{r}
ggplot() + 
  geom_sf(data = bernalillo_county)
```

```{r}
county_sub <- county_subdivisions(state = "NM", county = "Bernalillo", cb = TRUE, class = "sf") 
class(county_sub)
```

```{r}
blocks <- blocks(state = "NM", county = "Bernalillo", class = "sf") 
class(blocks)
```


## Organizing Data

```{r}
setwd("C:/Users/khali/OneDrive/Desktop/PhD coursework/Fall 2023/ERHS 535/Homework5")
homicides <- read_csv("data/homicide-data.csv")
head(x = homicides) 

albq_homicides <- homicides %>%             #Let's filter to only Albuquerque as the city
  filter(city %in% c("Albuquerque"))
albq_homicides
```


```{r}
albq_homicides <- homicides %>% 
  filter(city %in% c("Albuquerque")) %>%
  select(victim_race, lat, lon, disposition)
albq_homicides

albq_homicides2 <- na.omit(albq_homicides)
albq_homicides2
```


```{r}
albq_homicides2 <- st_as_sf(albq_homicides2, coords = c("lon", "lat")) %>% 
  st_set_crs(4269)
albq_homicides2 
```

## Map with shapes for disposition 



## Map with facet wrap for each disposition 
```{r}
ggplot() +
  geom_sf(data = bernalillo_county) +
  geom_sf(data = county_sub) +
  geom_sf(data = blocks) + 
  geom_sf(data = albq_homicides2, aes(color = victim_race,
                                  shape = disposition)) +
  facet_wrap(~ disposition, ncol = 3) +
  xlim(c(106.8, 106.4)) + ylim(c(35, 35.20))
```



+ 
  scale_color_viridis(name = "victim_race") 

